export{default as Navbar} from "./Navbar"
export{default as Hero} from "./Hero"
export{default as Memory} from "./Memory"
export{default as Explore} from "./Explore"
export{default as Advertisement} from "./Advertisement"
export{default as Footer} from "./Footer"
